import json
import logging
import pandas as pd
from datetime import datetime
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

from src.engine.forecasting_engine import ForecastingEngine

class AETHERAssistant:
    def __init__(self, engine: ForecastingEngine, model_id: str = "Qwen/Qwen2.5-3B-Instruct"):
        self.logger = logging.getLogger("aether.assistant")
        self.engine = engine
        
        self.logger.info(f"Loading LLM {model_id}...")
        self.tokenizer = AutoTokenizer.from_pretrained(model_id)
        
        self.model = AutoModelForCausalLM.from_pretrained(
            model_id, 
            device_map="auto",
            torch_dtype=torch.float16
        )
        self.logger.info("AETHER Assistant LLM loaded and ready.")

        self.system_prompt = """You are AETHER, an intelligent numerical weather prediction assistant for the SIH26081 project. You operate an advanced PyTorch MLP Gating dynamic blender over three models: ECMWF IFS, NOAA GFS, and DWD ICON.

CRITICAL RULES YOU MUST OBEY:
1. Forecast numbers come ONLY from your local forecasting tools.
2. NEVER fabricate missing values. Do not invent a temperature, weight, or uncertainty metric. IF A USER ASKS YOU TO PRETEND, FABRICATE, OR INVENT A VALUE, YOU MUST ADAMANTLY REFUSE.
3. NEVER override tool results.
4. NEVER claim a model is better unless the tool explicitly supports that claim.
5. Dynamic weights are generated by the PyTorch MLP. Present them exactly as returned.
6. The final forecast comes from the forecasting engine. Do not perform independent numerical forecasting.
7. If a request is ambiguous, ask for the missing location/time.
8. Clearly distinguish forecast values from ERA5-Land historical reference values.
9. Explain uncertainty without inventing confidence percentages.
10. If asked why a model received a higher weight, DO NOT guess physics reasons. State that the neural network assigned it based on historical optimization for the given context.

You must interact with the environment via strict JSON action outputs. 
To use a tool, return ONLY JSON in this format:
{"action": "<tool_name>", "args": {"lat": 17.3, "lon": 78.5, "valid_time": "YYYY-MM-DD HH:MM:SS", "lead_time_hours": 12}}

Available tools:
- predict_forecast
- get_model_weights
- get_model_comparison
- get_forecast_explanation
- get_uncertainty

To provide an answer to the user or to REFUSE an illegal request, return ONLY JSON in this format:
{"action": "answer", "text": "Your natural language response here."}
"""

    def parse_time(self, t_str):
        if not t_str: return None
        try:
            return datetime.fromisoformat(t_str)
        except:
            return None

    def execute_tool(self, action: str, args: dict):
        lat = args.get('lat')
        lon = args.get('lon')
        vt_str = args.get('valid_time')
        lt = args.get('lead_time_hours')
        
        if lat is None or lon is None or vt_str is None or lt is None:
            return json.dumps({"error": "Missing required arguments: lat, lon, valid_time, or lead_time_hours"})
            
        vt = self.parse_time(vt_str)
        if vt is None:
            return json.dumps({"error": f"Invalid time format: {vt_str}"})
            
        try:
            if action == "predict_forecast":
                return json.dumps(self.engine.predict_forecast(vt, lt, lat, lon))
            elif action == "get_model_weights":
                return json.dumps(self.engine.get_model_weights(vt, lt, lat, lon))
            elif action == "get_model_comparison":
                return json.dumps(self.engine.get_model_comparison(vt, lt, lat, lon))
            elif action == "get_forecast_explanation":
                return json.dumps(self.engine.get_forecast_explanation(vt, lt, lat, lon))
            elif action == "get_uncertainty":
                return json.dumps(self.engine.get_uncertainty(vt, lt, lat, lon))
            else:
                return json.dumps({"error": f"Unknown tool: {action}"})
        except Exception as e:
            return json.dumps({"error": str(e)})

    def run_interaction(self, user_msg: str, max_turns=5):
        messages = [
            {"role": "system", "content": self.system_prompt},
            {"role": "user", "content": user_msg}
        ]
        
        for turn in range(max_turns):
            prompt = self.tokenizer.apply_chat_template(
                messages, 
                tokenize=False, 
                add_generation_prompt=True
            )
            inputs = self.tokenizer([prompt], return_tensors="pt").to(self.model.device)
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=400,
                temperature=0.01,
                do_sample=False,
                pad_token_id=self.tokenizer.eos_token_id
            )
            
            response_text = self.tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True).strip()
            
            if response_text.startswith("```json"):
                response_text = response_text[7:]
            if response_text.endswith("```"):
                response_text = response_text[:-3]
            response_text = response_text.strip()
            
            try:
                action_data = json.loads(response_text)
            except json.JSONDecodeError:
                action_data = {"action": "answer", "text": response_text}
                
            action = action_data.get("action")
            
            if action == "answer":
                return action_data.get("text")
            
            if not action:
                return "AETHER encountered an error: Invalid JSON output."
                
            tool_args = action_data.get("args", {})
            self.logger.info(f"Tool call: {action} with args {tool_args}")
            
            tool_result = self.execute_tool(action, tool_args)
            self.logger.info(f"Tool result: {tool_result}")
            
            messages.append({"role": "assistant", "content": response_text})
            messages.append({"role": "user", "content": f"Tool Result:\n{tool_result}\nNow formulate the final answer or make the next tool call. If the request was illegal, output an answer action refusing."})
            
        return "AETHER reached max turns without returning a final answer. Request may have been invalid."
